import 'dart:ui';

class AlphabetModel {
  List<String> alphabet = [
    'alphabet/A.png',
    'alphabet/B.png',
    'alphabet/C.png',
    'alphabet/D.png',
    'alphabet/E.png',
    'alphabet/F.png',
    'alphabet/G.png',
    'alphabet/H.png',
    'alphabet/I.png',
    'alphabet/J.png',
    'alphabet/K.png',
    'alphabet/L.png',
    'alphabet/M.png',
    'alphabet/N.png',
    'alphabet/O.png',
    'alphabet/P.png',
    'alphabet/Q.png',
    'alphabet/R.png',
    'alphabet/S.png',
    'alphabet/T.png',
    'alphabet/U.png',
    'alphabet/V.png',
    'alphabet/W.png',
    'alphabet/X.png',
    'alphabet/Y.png',
    'alphabet/Z.png',
  ];
  List<Color> color = [
    const Color(0xff883070),
    const Color(0xff783878),
    const Color(0xff000000),
    const Color(0xff2860a0),
    const Color(0xff6f3609),
    const Color(0xff1068a8),
    const Color(0xff631e61),
    const Color(0xff17407c),
    const Color(0xff000070),
    const Color(0xff742749),
    const Color(0xff283c7f),
    const Color(0xff822a02),
    const Color(0xff384080),
    const Color(0xff683905),
    const Color(0xff541a01),
    const Color(0xff712e29),
    const Color(0xff002d55),
    const Color(0xff0050d8),
    const Color(0xff846400),
    const Color(0xff006498),
    const Color(0xffa71f32),
    const Color(0xffb54a10),
    const Color(0xff097011),
    const Color(0xff000000),
    const Color(0xff9d1e1e),
    const Color(0xff3f9e5a)
  ];

  List<String> alphabetAudio = [
    'alphabetAudio/a.mp4',
    'alphabetAudio/b.m4a',
    'alphabetAudio/c.m4a',
    'alphabetAudio/d.m4a',
    'alphabetAudio/e.m4a',
    'alphabetAudio/f.m4a',
    'alphabetAudio/g.m4a',
    'alphabetAudio/h.m4a',
    'alphabetAudio/i.m4a',
    'alphabetAudio/j.m4a',
    'alphabetAudio/k.m4a',
    'alphabetAudio/l.m4a',
    'alphabetAudio/m.m4a',
    'alphabetAudio/n.m4a',
    'alphabetAudio/o.m4a',
    'alphabetAudio/p.m4a',
    'alphabetAudio/q.m4a',
    'alphabetAudio/r.m4a',
    'alphabetAudio/s.m4a',
    'alphabetAudio/t.m4a',
    'alphabetAudio/u.m4a',
    'alphabetAudio/u.m4a',
    'alphabetAudio/w.m4a',
    'alphabetAudio/x.m4a',
    'alphabetAudio/y.m4a',
    'alphabetAudio/z.m4a',
  ];
  List<String> title = [
    'Axe',
    'Banana',
    'Cup',
    'Dolphin',
    'Egg',
    'Frog',
    'Grapes',
    'House',
    'Ice Cream',
    'Jelly Fish',
    'Kite',
    'Lion',
    'Moon',
    'Nest',
    'Owl',
    'Pencil',
    'Queen',
    'Rainbow',
    'Sun',
    'Train',
    'Umbrella',
    'Violin',
    'Watermelon',
    'X-Ray',
    'Yoyo',
    'Zebra'
  ];
}
